image: node:12

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - test
  - deploy-storybook

lint:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn lint

build:
  stage: build
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn build:lib

jest:
  stage: test
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    yarn test:unit --coverage
  artifacts:
    name: coverage
    paths:
      - coverage/
    expire_in: 30 days
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

deploy-storybook:
  stage: deploy-storybook
  only:
    - master
  before_script:
    - rm -rf .yarn
    - yarn install
  script:
    - yarn storybook:build
    - yarn storybook:deploy
